#!/bin/sh
# Looks in all parent directories for $1, and prints the full path to the first one found

arg="$1"
if test -z "$arg"; then exit 1; fi

while ! test -f "$arg"; do
 cd ..
 if test "$PWD" = "/"; then
    exit 1
 fi
done

echo $PWD/$arg

